# Generated by Django 4.2.7 on 2025-09-24 01:04

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="البريد الإلكتروني"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=150, verbose_name="الاسم الأول"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=150, verbose_name="الاسم الأخير"),
                ),
                (
                    "phone_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=128,
                        null=True,
                        region=None,
                        verbose_name="رقم الهاتف",
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("citizen", "مواطن له صوت انتخابي"),
                            ("parliament_candidate", "مرشح لعضوية مجلس النواب"),
                            ("senate_candidate", "مرشح لعضوية مجلس الشيوخ"),
                            ("parliament_member", "عضو حالي في مجلس النواب"),
                            ("senate_member", "عضو حالي في مجلس الشيوخ"),
                        ],
                        default="citizen",
                        max_length=20,
                        verbose_name="نوع المستخدم",
                    ),
                ),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("pending", "في انتظار التحقق"),
                            ("verified", "تم التحقق"),
                            ("rejected", "مرفوض"),
                        ],
                        default="pending",
                        max_length=10,
                        verbose_name="حالة التحقق",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="profile_pictures/",
                        verbose_name="الصورة الشخصية",
                    ),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, max_length=500, verbose_name="نبذة شخصية"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="تاريخ الميلاد"
                    ),
                ),
                (
                    "national_id",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        null=True,
                        unique=True,
                        verbose_name="الرقم القومي",
                    ),
                ),
                (
                    "governorate",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المحافظة"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="المدينة"
                    ),
                ),
                (
                    "is_email_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من البريد"
                    ),
                ),
                (
                    "is_phone_verified",
                    models.BooleanField(
                        default=False, verbose_name="تم التحقق من الهاتف"
                    ),
                ),
                (
                    "receive_notifications",
                    models.BooleanField(default=True, verbose_name="استقبال الإشعارات"),
                ),
                (
                    "google_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="معرف Google",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="تاريخ التحديث"),
                ),
                (
                    "last_login_ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="آخر IP للدخول"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "مستخدم",
                "verbose_name_plural": "المستخدمون",
                "db_table": "users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="LoginAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="البريد الإلكتروني"),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                ("success", models.BooleanField(default=False, verbose_name="نجح")),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="سبب الفشل"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ المحاولة"
                    ),
                ),
            ],
            options={
                "verbose_name": "محاولة تسجيل دخول",
                "verbose_name_plural": "محاولات تسجيل الدخول",
                "db_table": "login_attempts",
                "indexes": [
                    models.Index(
                        fields=["email", "created_at"],
                        name="login_attem_email_61a0cd_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "created_at"],
                        name="login_attem_ip_addr_f68fb5_idx",
                    ),
                    models.Index(
                        fields=["success"], name="login_attem_success_e73d81_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AnonymousSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                (
                    "pages_visited",
                    models.JSONField(default=list, verbose_name="الصفحات المزارة"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
            ],
            options={
                "verbose_name": "جلسة مجهولة",
                "verbose_name_plural": "الجلسات المجهولة",
                "db_table": "anonymous_sessions",
                "indexes": [
                    models.Index(
                        fields=["session_key"], name="anonymous_s_session_c7cb6e_idx"
                    ),
                    models.Index(
                        fields=["last_activity"], name="anonymous_s_last_ac_0d4574_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="UserSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        max_length=40, unique=True, verbose_name="مفتاح الجلسة"
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(verbose_name="عنوان IP")),
                (
                    "user_agent",
                    models.TextField(blank=True, verbose_name="معلومات المتصفح"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="نشط")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="تاريخ الإنشاء"
                    ),
                ),
                (
                    "last_activity",
                    models.DateTimeField(auto_now=True, verbose_name="آخر نشاط"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسة مستخدم",
                "verbose_name_plural": "جلسات المستخدمين",
                "db_table": "user_sessions",
                "indexes": [
                    models.Index(
                        fields=["user", "is_active"],
                        name="user_sessio_user_id_bb1b83_idx",
                    ),
                    models.Index(
                        fields=["session_key"], name="user_sessio_session_cc84b9_idx"
                    ),
                    models.Index(
                        fields=["last_activity"], name="user_sessio_last_ac_7cb421_idx"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["user_type"], name="users_user_ty_578f8f_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(
                fields=["verification_status"], name="users_verific_ff7924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
    ]
