# Generated by Django 4.2.7 on 2025-09-25 00:27

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('street_address', models.CharField(max_length=200, verbose_name='العنوان التفصيلي')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقم', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية')),
                ('council_type', models.CharField(choices=[('parliament', 'مجلس النواب'), ('senate', 'مجلس الشيوخ')], max_length=15, verbose_name='نوع المجلس')),
                ('constituency', models.CharField(max_length=100, verbose_name='الدائرة الانتخابية')),
                ('electoral_number', models.CharField(max_length=20, verbose_name='الرقم الانتخابي')),
                ('electoral_symbol', models.CharField(max_length=50, verbose_name='الرمز الانتخابي')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الواتساب')),
                ('bio', models.TextField(max_length=1000, verbose_name='السيرة الذاتية')),
                ('electoral_program', models.TextField(max_length=2000, verbose_name='البرنامج الانتخابي')),
                ('education', models.CharField(max_length=200, verbose_name='المؤهل العلمي')),
                ('occupation', models.CharField(max_length=100, verbose_name='المهنة')),
                ('experience', models.TextField(max_length=1000, verbose_name='الخبرات السابقة')),
                ('profile_picture', models.URLField(verbose_name='صورة الملف الشخصي')),
                ('banner_image', models.URLField(blank=True, verbose_name='صورة البانر')),
                ('cv_document', models.URLField(blank=True, verbose_name='السيرة الذاتية PDF')),
                ('campaign_slogan', models.CharField(blank=True, max_length=200, verbose_name='شعار الحملة')),
                ('campaign_website', models.URLField(blank=True, verbose_name='موقع الحملة')),
                ('campaign_facebook', models.URLField(blank=True, verbose_name='فيسبوك الحملة')),
                ('campaign_twitter', models.URLField(blank=True, verbose_name='تويتر الحملة')),
                ('is_approved', models.BooleanField(default=False, verbose_name='موافقة الإدارة')),
                ('approval_date', models.DateTimeField(blank=True, null=True, verbose_name='تاريخ الموافقة')),
                ('rating_average', models.FloatField(default=0.0, verbose_name='متوسط التقييم')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('messages_received', models.PositiveIntegerField(default=0, verbose_name='الرسائل المستلمة')),
                ('complaints_assigned', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المعينة')),
                ('complaints_solved', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المحلولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف المرشح',
                'verbose_name_plural': 'ملفات المرشحين',
            },
        ),
        migrations.CreateModel(
            name='CitizenProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('street_address', models.CharField(max_length=200, verbose_name='العنوان التفصيلي')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='الرمز البريدي')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقم', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الواتساب')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='المهنة')),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'ابتدائي'), ('secondary', 'ثانوي'), ('university', 'جامعي'), ('postgraduate', 'دراسات عليا')], max_length=15, verbose_name='المستوى التعليمي')),
                ('profile_picture', models.URLField(blank=True, verbose_name='صورة الملف الشخصي')),
                ('show_phone_public', models.BooleanField(default=False, verbose_name='إظهار الهاتف للعامة')),
                ('show_address_public', models.BooleanField(default=False, verbose_name='إظهار العنوان للعامة')),
                ('allow_messages', models.BooleanField(default=True, verbose_name='السماح بالرسائل')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تم التحقق')),
                ('verification_method', models.CharField(blank=True, choices=[('phone', 'رقم الهاتف'), ('email', 'البريد الإلكتروني'), ('national_id', 'الرقم القومي')], max_length=15, verbose_name='طريقة التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
                ('messages_sent', models.PositiveIntegerField(default=0, verbose_name='الرسائل المرسلة')),
                ('complaints_submitted', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المقدمة')),
                ('ratings_given', models.PositiveIntegerField(default=0, verbose_name='التقييمات المعطاة')),
            ],
            options={
                'verbose_name': 'ملف المواطن',
                'verbose_name_plural': 'ملفات المواطنين',
            },
        ),
        migrations.CreateModel(
            name='CurrentMemberProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='المدينة')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='الحي')),
                ('street_address', models.CharField(max_length=200, verbose_name='العنوان التفصيلي')),
                ('national_id', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator(message='الرقم القومي يجب أن يكون 14 رقم', regex='^\\d{14}$')], verbose_name='الرقم القومي')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], max_length=10, verbose_name='النوع')),
                ('birth_date', models.DateField(verbose_name='تاريخ الميلاد')),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'أعزب'), ('married', 'متزوج'), ('divorced', 'مطلق'), ('widowed', 'أرمل')], max_length=10, verbose_name='الحالة الاجتماعية')),
                ('council_type', models.CharField(choices=[('parliament', 'مجلس النواب'), ('senate', 'مجلس الشيوخ')], max_length=15, verbose_name='نوع المجلس')),
                ('constituency', models.CharField(max_length=100, verbose_name='الدائرة الانتخابية')),
                ('membership_start_date', models.DateField(verbose_name='تاريخ بداية العضوية')),
                ('term_number', models.PositiveIntegerField(verbose_name='رقم الدورة')),
                ('seat_number', models.CharField(blank=True, max_length=10, verbose_name='رقم المقعد')),
                ('committees', models.TextField(blank=True, max_length=500, verbose_name='اللجان المشارك فيها')),
                ('positions', models.TextField(blank=True, max_length=300, verbose_name='المناصب الحالية')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='رقم الواتساب')),
                ('bio', models.TextField(max_length=1000, verbose_name='السيرة الذاتية')),
                ('achievements', models.TextField(max_length=2000, verbose_name='الإنجازات')),
                ('education', models.CharField(max_length=200, verbose_name='المؤهل العلمي')),
                ('occupation', models.CharField(max_length=100, verbose_name='المهنة')),
                ('experience', models.TextField(max_length=1000, verbose_name='الخبرات السابقة')),
                ('profile_picture', models.URLField(verbose_name='صورة الملف الشخصي')),
                ('banner_image', models.URLField(blank=True, verbose_name='صورة البانر')),
                ('official_cv', models.URLField(blank=True, verbose_name='السيرة الذاتية الرسمية')),
                ('office_address', models.TextField(blank=True, max_length=300, verbose_name='عنوان المكتب')),
                ('office_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='هاتف المكتب')),
                ('office_hours', models.CharField(blank=True, max_length=100, verbose_name='ساعات العمل')),
                ('rating_average', models.FloatField(default=0.0, verbose_name='متوسط التقييم')),
                ('rating_count', models.PositiveIntegerField(default=0, verbose_name='عدد التقييمات')),
                ('messages_received', models.PositiveIntegerField(default=0, verbose_name='الرسائل المستلمة')),
                ('complaints_handled', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المعالجة')),
                ('complaints_solved', models.PositiveIntegerField(default=0, verbose_name='الشكاوى المحلولة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'ملف العضو الحالي',
                'verbose_name_plural': 'ملفات الأعضاء الحاليين',
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم المحافظة')),
                ('name_en', models.CharField(max_length=50, verbose_name='الاسم بالإنجليزية')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='كود المحافظة')),
            ],
            options={
                'verbose_name': 'محافظة',
                'verbose_name_plural': 'المحافظات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم الحزب')),
                ('name_en', models.CharField(max_length=100, verbose_name='الاسم بالإنجليزية')),
                ('abbreviation', models.CharField(max_length=20, verbose_name='الاختصار')),
            ],
            options={
                'verbose_name': 'حزب',
                'verbose_name_plural': 'الأحزاب',
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='AnonymousSession',
        ),
        migrations.DeleteModel(
            name='LoginAttempt',
        ),
        migrations.RemoveField(
            model_name='usersession',
            name='user',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_email_4b85f2_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_ty_578f8f_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_verific_ff7924_idx',
        ),
        migrations.RemoveIndex(
            model_name='user',
            name='users_created_6541e9_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
        migrations.RemoveField(
            model_name='user',
            name='city',
        ),
        migrations.RemoveField(
            model_name='user',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='governorate',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='last_login_ip',
        ),
        migrations.RemoveField(
            model_name='user',
            name='national_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='profile_picture',
        ),
        migrations.RemoveField(
            model_name='user',
            name='receive_notifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='user',
            name='last_active',
            field=models.DateTimeField(auto_now=True, verbose_name='آخر نشاط'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأول'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='الاسم الأخير'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='auth_user',
        ),
        migrations.DeleteModel(
            name='UserSession',
        ),
        migrations.AddField(
            model_name='currentmemberprofile',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='currentmemberprofile',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.party', verbose_name='الحزب'),
        ),
        migrations.AddField(
            model_name='currentmemberprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='citizenprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_candidates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='governorate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.governorate', verbose_name='المحافظة'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='users.party', verbose_name='الحزب'),
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
